server:
  port: 10010
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        #路由id，可以任意
        - id: user-service-route
          #代理服务地址
          uri:
            lb://user-service
          #路径断言,可以匹配映射路径
          predicates:
            - Path=/api/user/**,/api/role/**
        - id: shop-service-route
          uri:
            lb://shop-service
          predicates:
            - Path=/api/mall-product/**,/api/mall-product-type/**,/api/mall-product-brand/**
        - id: order-service-route
          uri:
            lb://order-service
          predicates:
            - Path=/api/oderpay/**,/api/mall-order-detail/**,/api/mall-order/**
        - id: cart-service
          uri:
            lb://cart-service
          predicates:
            - Path=/api/mall-cart/**,/api/mall-address/**
        - id: oss-service
          uri: lb://oss-service
          predicates:
            - Path=/api/file/**
#          filters:
#            #1表示过滤一个路径，2表示过滤两个（以此类推）
#            - StripPrefix=1
#            #添加请求路径的前缀
#            #- PrefixPath=/user
#            #默认过滤器，对所有路由生效
#            - MyParam=name
#      default-filters:
#        - AddResponseHeader=X-Response-Foo,Bar
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*" # 这种写法或者下面的都可以，*表示全部
#            allowedOrigins:
#              - "http://docs.spring.io"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000
ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 2000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0